"""Add cancel_reason to Reservation

Revision ID: 1e61bbfa5e70
Revises: 
Create Date: 2026-04-10 03:42:21.995568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e61bbfa5e70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('payment')
    op.drop_constraint('order_reservation_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'reservation_id')
    op.add_column('reservation', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.drop_constraint('fk_user', 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    op.drop_column('reservation', 'cancellation_reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('cancellation_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key('fk_user', 'reservation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reservation', 'cancel_reason')
    op.add_column('order', sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_reservation_id_fkey', 'order', 'reservation', ['reservation_id'], ['id'])
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='payment_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_pkey')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    sa.UniqueConstraint('name', name='category_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
