"""Add preorder_data to Reservation

Revision ID: c6cdc89bc0b8
Revises: 1e61bbfa5e70
Create Date: 2026-04-10 04:02:36.737267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cdc89bc0b8'
down_revision = '1e61bbfa5e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('preorder_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'preorder_data')
    # ### end Alembic commands ###
